# ex04_test_all.rb
# frozen_string_literal: true

require_relative "ex04.rb"

def show(title)
  puts "\n=== #{title} ==="
end

# 1) 基本雙標籤結構：Html / Head / Body / Title / H1 / Img
show "Document skeleton"
doc = Html.new([
  Head.new([
    Title.new("Hello ground!"),
    Meta.new({ "charset" => "UTF-8" }),
    Meta.new({ "name" => "viewport", "content" => "width=device-width" })
  ]),
  Body.new([
    H1.new("Oh no, not again!"),
    P.new("This page is generated by ex04_test.rb"),
    Div.new([
      P.new("Inside a Div: paragraph 1"),
      P.new("Inside a Div: paragraph 2"),
      Span.new("Inside a Div: span text")
    ]),
    Ul.new([
      Li.new("Ul item 1"),
      Li.new("Ul item 2"),
      Li.new("Ul item 3")
    ]),
    Ol.new([
      Li.new("Ol item 1"),
      Li.new("Ol item 2"),
      Li.new("Ol item 3")
    ]),
    Table.new([
      Tr.new([Th.new("Name"), Th.new("Age")]),
      Tr.new([Td.new("Ada"), Td.new("42")]),
      Tr.new([Td.new("Grace"), Td.new("85")])
    ]),
    Img.new([], { "src" => "http://i.imgur.com/pfp3T.jpg", "alt" => "pfp" }),
    Hr.new,
    Br.new
  ])
])
puts doc

# 將完整文件輸出成 HTML 檔案（方便用瀏覽器打開）
output_path = File.join(__dir__, "ex04_test_output.html")
File.write(output_path, doc.to_s + "\n")
puts "\n[OK] HTML file generated: #{output_path}"

# 2) H2 / P / Span / Div（文字自動轉 Text）
show "Text-ish nodes"
puts H2.new("Subtitle")
puts P.new("A paragraph")
puts Span.new("inline text")
puts Div.new([P.new("inside div"), Span.new("span in div")])

# 3) List：Ul / Ol / Li
show "Lists"
puts Ul.new([Li.new("u1"), Li.new("u2")])
puts Ol.new([Li.new("o1"), Li.new("o2"), Li.new("o3")])

# 4) Table：Table / Tr / Th / Td
show "Table"
table = Table.new([
  Tr.new([Th.new("Name"), Th.new("Age")]),
  Tr.new([Td.new("Ada"), Td.new("42")])
])
puts table

# 5) Simple tags：Meta / Img / Hr / Br（確認自閉合與屬性）
show "Simple tags"
puts Meta.new({ "name" => "viewport", "content" => "width=device-width" })
puts Img.new([], { "src" => "x.png" })
puts Hr.new({ "class" => "sep" })
puts Br.new